- name: Hello World Playbook with Prometheus Metrics
  hosts: localhost
  tasks:
    - name: Print Hello World
      debug:
        msg: "Hello, World!"
    - name: Send success status to Prometheus Pushgateway
      uri:
        url: "http://localhost:9091/metrics/job/ansible_hello"
        method: POST
        body: |
          # TYPE ansible_playbook_success gauge
          ansible_playbook_success 1
        headers:
          Content-Type: "text/plain"
